swagger: '2.0'

info:
  version: '1.0.0'
  title: Repair Orders
  description: |
    ## Fortellis - Service - Repair Orders
    Repair Orders allow service personnel to record work being done on a vehicle.

    # What does this API do?
      The API will provide the ability to read Repair Orders. The API sets a common data model for Repair Orders in order for different solutions to be able to easily integrate Repair Order solutions.

    # Intended Audience
    It is intended for solutions (apps or services) to be able to retrieve Repair Orders.
  contact:
    name: CDK Global
    url: https://cdkglobal.com
    email: info@cdk.com

host: api.fortellis.io
basePath: /service/v1/repair-orders

securityDefinitions:
  permission-model:
    type: oauth2
    flow: implicit
    authorizationUrl: https://identity.fortellis.io/oauth2/

schemes:
 - https

paths:
  /:
    get:
      summary: Get list of Repair Orders
      description: |
        Returns a list of Repair Orders for a dealership.

        Using the `Prefer` header attribute of `minimal` will return Repair Orders without Repair Order Service Lines.

        Using the `Prefer` header attribute of `representation` will return Repair Order with Repair Order Service Lines.

        When no `Prefer` header attribute is set it would default to `minimal`.
      operationId: listRepairOrders
      tags:
        - repair orders
      parameters:
        - $ref: '#/parameters/header.Subscription-Id'
        - $ref: '#/parameters/header.Request-Id'
        - $ref: '#/parameters/header.Authorization'
        - $ref: '#/parameters/header.Prefer'
        - $ref: '#/parameters/query.page'
        - $ref: '#/parameters/query.pageSize'
        - $ref: '#/parameters/query.dateTimeInterval'
        - $ref: '#/parameters/query.repairOrderStatus'      
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          $ref: '#/responses/RepairOrders'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
        '503':
          $ref: '#/responses/ServiceUnavailable'


  /{repairOrderId}:
    get:
      summary: Retrieve a Repair Order
      description: |
        Retrieve a Repair Order by an identifier.

        Using the `Prefer` header attribute of `minimal` will return a Repair Order without Repair Order Service Lines.

        Using the `Prefer` header attribute of `representation` will return Repair Order with Repair Order Service Lines.
      operationId: retrieveRepairOrder
      tags:
        - repair orders
      parameters:
        - $ref: '#/parameters/header.Subscription-Id'
        - $ref: '#/parameters/header.Request-Id'
        - $ref: '#/parameters/header.Authorization'      
        - $ref: '#/parameters/header.Prefer'      
        - $ref: '#/parameters/path.repairOrderId'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          $ref: '#/responses/RepairOrder'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
        '404':
          $ref: '#/responses/NotFound'
        '503':
          $ref: '#/responses/ServiceUnavailable'

parameters:
  # Common Parameters (see common.yaml)
  header.Subscription-Id:
    name: Subscription-Id
    in: header
    required: true
    type: string
    description: The Fortellis Marketplace subscription identifier between a user entity and the solution.
      For sample responses use the Subscription-Id 'test'.

  header.Authorization:
    name: Authorization
    in: header
    required: true
    type: string
    description: Provides authorization to access Fortellis APIs. For calling a Fortellis Provider,
      this must be an OAuth 2.0 token issued by the Fortellis authorization server, but you may call
      the simulator platform with Basic Authorization using your API key and secret.

  header.Request-Id:
    name: Request-Id
    in: header
    required: true
    type: string
    format: guid
    description: A correlation ID that should be returned back to the caller to indicate the return of the
      given request.

  header.Prefer:
    name: Prefer
    in: header
    required: false
    type: string
    enum:
      - return=representation
      - return=minimal
    default: return=minimal
    description: Advertises whether the whole entity should be returned or a minimal subset of the entity should be returned.

  path.repairOrderId:
    in: path
    name: repairOrderId    
    required: true
    type: string
    description: The repair order identifier.

  query.page:
    name: page
    in: query
    type: integer
    format: int32
    minimum: 1
    description: This is a pagination control for the request page of query result items to return in the response. It must be greater than or equal to one. If greater than the total number of available pages, the returned page will be the last available page.

  query.pageSize:
    name: pageSize
    in: query
    type: integer
    format: int32
    minimum: 1
    description: This is a pagination control for the requested number of items returned per page. It must be greater than or equal to one. This may be overridden and clamped to a maximum value by the resource owner.
  
  query.repairOrderStatus:
    name: status
    in: query
    type: string
    description: This is the the Repair Order Status 
    enum:
      - PENDING
      - CLOSED
      - DELETED
      - CREATED
      - APPROVED
      - REJECTED
      - CANCELED
      - DISPATCHED
      - ON_HOLD_APPROVAL
      - ON_HOLD_LABOR
      - ON_HOLD_PARTS
      - IN_PROGRESS
      - COMPLETED

  query.dateTimeInterval:
    name: dateTimeInterval
    in: query
    required: true
    type: string
    description: The ISO 8601 encoded date and time interval to filter the Repair Orders
    
responses:
  RepairOrder:
    description: OK
    headers:
      Request-Id:
        type: string
    schema:
      $ref: '#/definitions/RepairOrder'

  RepairOrders:
    description: OK
    headers:
      Request-Id:
        type: string
    schema:
      $ref: '#/definitions/RepairOrderCollection'

  # Common Responses (see common.yaml)
  Success:
    description: 204 - No Content
    headers:
      Request-Id:
        type: string

  BadRequest:
    description: 400 - Bad Request
    headers:
      Request-Id:
        type: string
    schema:
      $ref: '#/definitions/ErrorResponse'

  Unauthorized:
    description: 401 - Unauthorized
    headers:
      Request-Id:
        type: string
    schema:
      $ref: '#/definitions/ErrorResponse'

  Forbidden:
    description: 403 - Forbidden
    headers:
      Request-Id:
        type: string
    schema:
      $ref: '#/definitions/ErrorResponse'

  NotFound:
    description: 404 - Not Found
    headers:
      Request-Id:
        type: string
    schema:
      $ref: '#/definitions/ErrorResponse'

  Locked:
    description: 423 - Locked
    headers:
      Request-Id:
        type: string
    schema:
      $ref: '#/definitions/ErrorResponse'

  ServiceUnavailable:
    description: 503 - Service Unavailable
    headers:
      Request-Id:
        type: string
    schema:
      $ref: '#/definitions/ErrorResponse'

definitions:
# Repair Order Models
  RepairOrder:
    description: Defines a Repair Order.
    type: object     
    properties:
      repairOrderId:
        description: Primary key identifying a specific Repair Order.
        type: string
      createdDateTime:
        description: The ISO 8601 encode date and time of when the repair order was created
        type: string
        format: date-time  
      mileageIn:
        $ref: '#/definitions/Measurement'
        description: Mileage measurement when the vehicle arrived for service.
      advisor:
        $ref: '#/definitions/Advisor'
      vehicle:
        $ref: '#/definitions/Vehicle'
      serviceLines:
        type: array
        items:
          $ref: '#/definitions/ServiceLine'
    required:
      - repairOrderId
    example:
      repairOrderId: '2345678'
      createDateTime: '2020-07-15T23:44:57+00:00'
      mileageIn:
        value: 1000
        units: 'KM'
      advisor:
        advisorId: '435678'
        name:
          first: 'John'
          last: 'Smith'
      vehicle:
        vin: '1J4HR58N96C336690'
      serviceLines:
        - serviceLineId: '3456'
          description: 'Replace Engine Oil'
          inspectionId: '2456783'
          serviceRecommendationType: 'OEM'
          approvalState: 'APPROVED'
          serviceOperationCode: 'GEN'
          flatRateHours: 10
          mpiInspectionPoint:
            inspectionPointId: '1'
            categoryName: 'Tread Depth'
            name: 'Front Left Tire Tread Depth'
            description: 'The tread depth of the front left tire of the vehicle.'
            severity: 'RED'
            values:
              - '1'
            metadata:
              - metadataId: '1'
                key: 'INSPECTION_ID'
                value: 'TIRES_LF'
          pricing:
            currencyCode: 'USD'
            total: 10.00

  Advisor:
    description: The assigned advisor
    type: object
    allOf:
      - properties:
          advisorId:
            description: The advisor unique identifer.
            type: string
          name:
            $ref: '#/definitions/Name'
    required:
      - advisorId
      - name
    example:
      advisorId: '435678'
      name:
        first: 'John'
        last: 'Smith'
  Vehicle:
    description: Vehicle Summary.
    type: object
    properties:
      vin:
        type: string
        description: The vehicle identification number (VIN)
        minLength: 11
        maxLength: 17
    required:
      - vin
    example:
      vin: '1J4HR58N96C336690'

# Service Line Models
  ServiceLine:
    description: Defines a Service Line.
    type: object
    allOf:      
      - $ref: '#/definitions/ServiceLineInfo'
      - properties:
          serviceLineId:
            description: The service item unique identifier.
            type: string
          mpiInspectionPoint:
           $ref: '#/definitions/InspectionPoint'
          pricing:
            $ref: '#/definitions/ServiceLinePricing'
          menuServiceLines:
            type: array
            items:
              $ref: '#/definitions/MenuServiceLine'
    required:
      - serviceLineId
      - description
      - serviceRecommendationType
    example:
      serviceLineId: '3456'
      description: 'Replace Engine Oil'
      inspectionId: '2456783'
      serviceRecommendationType: 'OEM'
      approvalState: 'APPROVED'
      serviceOperationCode: 'GEN'
      flatRateHours: 10
      mpiInspectionPoint:
        inspectionPointId: '1'
        categoryName: 'Tread Depth'
        name: 'Front Left Tire Tread Depth'
        description: 'The tread depth of the front left tire of the vehicle.'
        severity: 'RED'
        values:
          - '1'
        metadata:
          - metadataId: '1'
            key: 'INSPECTION_ID'
            value: 'TIRES_LF'
      menuServiceLines:
        - menuServiceLineId: '45555'
          description: 'Oil Filter Replacement'
          serviceRecommendationType: 'OEM'
          approvalState: 'APPROVED'
          serviceOperationCode: 'PART'
          flatRateHours: 4
      pricing:
        currencyCode: 'USD'
        total: 10.00

  ServiceLineInfo:
    description: Basic properties of a ServiceLine.
    type: object
    properties:
      description:
        description: The description of the service.
        type: string
      inspectionId:
        description: The Multipoint Inspection unique identifier that is related to this service.
        type: string
      serviceRecommendationType:
        description: States whether the service is recommended by the DEALER or OEM.
        type: string
        enum:
          - DEALER
          - OEM
      serviceOperationCode:
        description: Operation code representing the requested service.
        type: string
      approvalState:
        description: Approval state of the Service Line.
        type: string
        enum:
          - NOT_SET
          - PENDING
          - APPROVED
          - DECLINED
      flatRateHours:
        description: Flat Rate Hours for the service used to calculate line pricing
        type: number
    required:
      - description
      - serviceRecommendationType
      - approvalState
    example:
      description: 'Replace Engine Oil'
      serviceRecommendationType: 'OEM'
      approvalState: 'APPROVED'
      serviceOperationCode: 'GEN'
      flatRateHours: 10

  MenuServiceLine:
    description: Defines a Menu Service Line.
    type: object
    allOf:      
      - $ref: '#/definitions/ServiceLineInfo'
      - properties:
          menuServiceLineId:
            description: The service item unique identifier.
            type: string
          pricing:
            $ref: '#/definitions/ServiceLinePricing'
    required:
      - menuServiceLineId
      - description
      - serviceRecommendationType
    example:
      menuServiceLineId: '3456'
      description: 'Replace Engine Oil'
      serviceRecommendationType: 'OEM'
      approvalState: 'APPROVED'
      serviceOperationCode: 'GEN'
      flatRateHours: 10
      pricing:
        currencyCode: 'USD'
        total: 10.00

  ServiceLinePricing:
    description: Service Line Pricing
    type: object
    properties:
      currencyCode:
        type: string
        description: The ISO 4217 three letter currency code of the price
      total:  
        type: number
        description: Total price including sales tax / VAT expressed in the given currency.
    required:
      - total
    example:
      currencyCode: 'USD'
      total: 200

# Inspection Models
  InspectionPoint:
    description: The associated Inspection Point result for the Service Line
    type: object
    properties:
      inspectionPointId:
        description: The Inspection Point unique identifier
        type: string
      categoryName:
        description: Name of the Inspection Category.
        type: string  
      name:
        description: Name of an Inspection Point.
        type: string
      description:
        description: Description of the Inspection Point.
        type: string
      severity:
        description: The identifier of the Severity set on the Inspection Point.
        type: string
        enum:
          - RED
          - AMBER
          - GREEN
          - UNCHECKED
      values:
        description: List of values stored on the Inspection Point.
        type: array
        items:
          type: string
          description: A value associated with an Inspection Point.
      metadata:
        description: List of Metadata associated to the Inspection Point.
        type: array
        items:
          $ref: '#/definitions/Metadata'
    required:
      - inspectionPointId
      - name
      - values
    example:
      inspectionPointId: '1'
      categoryName: 'Tread Depth'
      name: 'Front Left Tire Tread Depth'
      description: 'The tread depth of the front left tire of the vehicle.'
      severity: 'RED'
      values:
        - '1'
      metadata:
        - metadataId: '1'
          key: 'INSPECTION_ID'
          value: 'TIRES_LF'

  Metadata:
    description: Metadata related to an entity represented as a key/value pair.
    type: object
    properties:
      metadataId:
        description: Primary Key
        type: string        
      key: 
        description: The key to identify the data.
        type: string
      value:
        description: The data value.
        type: string     
    required:
      - metadataId
      - key
      - value
    example:
      metadataId: '1'
      key: 'INSPECTION_ID'
      value: 'TIRES_LF'

  # Collections
  RepairOrderCollection:
    description: A collection of Repair Orders.
    type: object
    allOf:
      - $ref: '#/definitions/BaseCollection'
      - properties:
          items:
            type: array
            items:
              $ref: '#/definitions/RepairOrder'
    required:
      - items
    example:
      totalItems: 1
      totalPages: 1
      links:
        firstPage:
          href: https://api.fortellis.io/service/v1/inspections/definitions?page=1&pageSize=20
          method: GET
          title: Get the first page of results
      items:
      - repairOrderId: '2345678'
        mileageIn:
          value: 1000
          units: 'KM'
        advisor:
          advisorId: '435678'
          name:
            first: 'John'
            last: 'Smith'
        serviceLines:
          - serviceLineId: '3456'
            description: 'Replace Engine Oil'
            inspectionId: '2456783'
            serviceRecommendationType: 'OEM'
            approvalState: 'APPROVED'
            serviceOperationCode: 'GEN'
            flatRateHours: 10
            mpiInspectionPoint:
              inspectionPointId: '1'
              categoryName: 'Tread Depth'
              name: 'Front Left Tire Tread Depth'
              description: 'The tread depth of the front left tire of the vehicle.'
              severity: 'RED'
              values:
                - '1'
              metadata:
                - metadataId: '1'
                  key: 'INSPECTION_ID'
                  value: 'TIRES_LF'
            menuServiceLines:
              - menuServiceLineId: '45555'
                description: 'Oil Filter Replacement'
                serviceRecommendationType: 'OEM'
                approvalState: 'APPROVED'
                serviceOperationCode: 'PART'
                flatRateHours: 4
            pricing:
              currencyCode: 'USD'
              total: 10.00

  # Common Definitions (see common.yaml)
  Name:
    type: object
    description: The name of a person.
    properties:
      first:
        type: string
        description: The first name of the customer.
      last:
        type: string
        description: The last name of the customer.
    required:
      - first
      - last
    example:
      first: 'John'
      last: 'Smith'

  Measurement:
    description: Defines a Measurement.
    properties:
      value:
        type: number
        description: The measurement value.
      units:
        type: string
        enum:
          - MI
          - KM
          - HR
        description: The units of measurement.
    required:
      - value
      - units
    example:
      value: 1000.00
      units: 'KM'

  ErrorResponse:
    description: Details of a general error response.
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
    required:
      - code
      - message
    example:
      code: 404
      message: 'An error has occurred'

  BaseCollection:
    description: Definition of properties required for paginated returned lists and totals.
    type: object
    properties:
      totalItems:
        type: integer
        format: int32
        description: The total number of items contained in the collection.
      totalPages:
        type: integer
        format: int32
        description: The total number of pages given the requested page size.
      links:
        $ref: '#/definitions/BaseCollectionLinks'
        description: The hypermedia links describing the possible resource actions
    required:
      - totalItems
      - totalPages
      - links
    example:
      totalItems: 2
      totalPages: 1
      links:
        firstPage:
          href: https://api.fortellis.io/domain/sub-domain/v0/resource?page=1&pageSize=20
          method: GET
          title: Get the first page of results
        nextPage:
          href: https://api.fortellis.io/domain/sub-domain/v0/resource?page=1&pageSize=20
          method: GET
          title: Get the next page of results
        prevPage:
          href: https://api.fortellis.io/domain/sub-domain/v0/resource?page=2&pageSize=20
          method: GET
          title: Get the previous page of results

  BaseCollectionLinks:
    description: Definition of properties required for paginated returned lists.
    type: object
    properties:
      nextPage:
        description: The next page of query results.
        $ref: '#/definitions/LinkDescriptionObject'
      prevPage:
        description: The previous page of query results.
        $ref: '#/definitions/LinkDescriptionObject'
      firstPage:
        description: The first page of query results.
        $ref: '#/definitions/LinkDescriptionObject'
    required:
      - firstPage
    example:
      firstPage:
        href: https://api.fortellis.io/domain/sub-domain/v0/resource?page=1&pageSize=20
        method: GET
        title: Get the first page of results
      nextPage:
        href: https://api.fortellis.io/domain/sub-domain/v0/resource?page=4&pageSize=20
        method: GET
        title: Get the next page of results
      prevPage:
        href: https://api.fortellis.io/domain/sub-domain/v0/resource?page=2&pageSize=20
        method: GET
        title: Get the previous page of results

  LinkDescriptionObject:
    description: Details of a link to a resource.
    type: object
    properties:
      href:
        type: string
        description: The target URI.
      method:
        type: string
        description: The HTTP verb that MUST be used to make a request to the target of the link.
      title:
        type: string
        description: A human readable title for the link that conveys the purpose of the link.
    required:
      - href
    example:
      href: https://api.fortellis.io/domain/sub-domain/v0/resource?page=2&pageSize=20
      method: GET
      title: Get the previous page of results
  